# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"


# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig="nvim ~/.zshrc"
alias ohmyzsh="nvim ~/.oh-my-zsh"

alias java11="export JAVA_HOME=/Users/leeturner/Library/Java/JavaVirtualMachines/azul-11.0.25/Contents/Home"
alias java17="export JAVA_HOME=/Users/leeturner/Library/Java/JavaVirtualMachines/azul-17.0.13/Contents/Home"
alias java21="export JAVA_HOME=/Users/leeturner/Library/Java/JavaVirtualMachines/graalvm-ce-21.0.2/Contents/Home"
alias java23="export JAVA_HOME=/Users/leeturner/Library/Java/JavaVirtualMachines/openjdk-23.0.1/Contents/Home"

export GRAALVM_HOME=/Users/leeturner/Library/Java/JavaVirtualMachines/graalvm-ce-21.0.2/Contents/Home

alias mothership="cd ~/dev/wiremock-inc/mothership"
alias ui="cd ~/dev/wiremock-inc/ui"
alias cli="cd ~/dev/wiremock-inc/wiremock-cli"
alias mockhost="cd ~/dev/wiremock-inc/mock-host"
alias admin="cd ~/dev/wiremock-inc/admin"
alias openapi="cd ~/dev/wiremock-inc/openapi"

mvu() {
    mv ~/Downloads/$1 .
    unzip $1
    rm ./$1
}

export PATH=/Users/leeturner/.local/bin:$PATH
export PATH=/Applications/chromedriver-mac-arm64:$PATH
export PATH=$GRAALVM_HOME/bin:$PATH
export PATH=$PATH:/Applications/roc_nightly-macos_apple_silicon-2025-09-09-d73ea109cc2
export PATH=$PATH:/Applications/v

eval "$(starship init zsh)"
eval "$(direnv hook zsh)"

source $(brew --prefix asdf)/libexec/asdf.sh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
. $(brew --prefix asdf)/libexec/asdf.sh

source /Users/leeturner/.config/wiremock-cli/command-completion.zsh

eval "$(zoxide init zsh)"
